import React from 'react';

// import ArrowDownIcon_ from '../assets/icons/arrow-down.svg';
// import BuisnessProcessesIcon_ from '../assets/icons/buisness-processes.svg';
// import CaretIcon_ from '../assets/icons/caret.svg';
// import CheckMarkIcon_ from '../assets/icons/check-mark.svg';
// import CrossIcon_ from '../assets/icons/cross.svg';
// import DotsIcon_ from '../assets/icons/dots.svg';
// import ExitIcon_ from '../assets/icons/exit.svg';
// import EyeClosedIcon_ from '../assets/icons/eye-closed.svg';
// import EyeIcon_ from '../assets/icons/eye.svg';
// import HomeIcon_ from '../assets/icons/home.svg';
// import IMarkIcon_ from '../assets/icons/i-mark.svg';
// import PlayIcon_ from '../assets/icons/play.svg';
// import PlusIcon_ from '../assets/icons/plus.svg';
// import RuntimeEnvironmentsIcon_ from '../assets/icons/runtime-environments.svg';
// import SearchIcon_ from '../assets/icons/search.svg';
// import ServersIcon_ from '../assets/icons/servers.svg';
// import ServicesIcon_ from '../assets/icons/services.svg';
// import SettingsIcon_ from '../assets/icons/settings.svg';
// import SoftwareIcon_ from '../assets/icons/software.svg';
// import StartBlueIcon_ from '../assets/icons/start-blue.svg';
// import StartsIcon_ from '../assets/icons/starts.svg';
// import StopIcon_ from '../assets/icons/stop.svg';
// import StrokeIcon_ from '../assets/icons/stroke.svg';
// import TasksIcon_ from '../assets/icons/tasks.svg';
// import TrashIcon_ from '../assets/icons/trash.svg';
// import TriggersIcon_ from '../assets/icons/triggers.svg';
// import UsersIcon_ from '../assets/icons/users.svg';
// import WarningIcon_ from '../assets/icons/warning.svg';
// import WorksTuzIcon_ from '../assets/icons/works-tuz.svg';
// import XMarkSmallIcon_ from '../assets/icons/x-mark-small.svg';
// import XMarkIcon_ from '../assets/icons/x-mark.svg';
// import CaretSmallIcon_ from '../assets/icons/caret-small.svg';

// // console.log('CaretSmallIcon_', CaretSmallIcon_);

// const SvgImg = ({ ...args }) => {
//     const { svg, alt = '' } = args;
//     delete args.svg;
//     delete args.alt;
//     return <img {...args} alt={alt} src={svg} />;
// };

export const ArrowDownIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={ArrowDownIcon_} />;
export const BuisnessProcessesIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={BuisnessProcessesIcon_} />;
export const CaretIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={CaretIcon_} />;
export const CheckMarkIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={CheckMarkIcon_} />;
export const CrossIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={CrossIcon_} />;
export const DotsIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={DotsIcon_} />;
export const ExitIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={ExitIcon_} />;
export const EyeClosedIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={EyeClosedIcon_} />;
export const EyeIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={EyeIcon_} />;
export const HomeIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={HomeIcon_} />;
export const IMarkIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={IMarkIcon_} />;
export const PlayIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={PlayIcon_} />;
export const PlusIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={PlusIcon_} />;
export const RuntimeEnvironmentsIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={RuntimeEnvironmentsIcon_} />;
export const SearchIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={SearchIcon_} />;
export const ServersIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={ServersIcon_} />;
export const ServicesIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={ServicesIcon_} />;
export const SettingsIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={SettingsIcon_} />;
export const SoftwareIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={SoftwareIcon_} />;
export const StartBlueIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={StartBlueIcon_} />;
export const StartsIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={StartsIcon_} />;
export const StopIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={StopIcon_} />;
export const StrokeIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={StrokeIcon_} />;
export const TasksIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={TasksIcon_} />;
export const TrashIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={TrashIcon_} />;
export const TriggersIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={TriggersIcon_} />;
export const UsersIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={UsersIcon_} />;
export const WarningIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={WarningIcon_} />;
export const WorksTuzIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={WorksTuzIcon_} />;
export const XMarkSmallIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={XMarkSmallIcon_} />;
export const XMarkIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={XMarkIcon_} />;
export const CaretSmallIcon = (...args: any) => <p {...args}>args</p>; // <SvgImg {...args} svg={CaretSmallIcon_} />;
