import React from 'react';

import ArrowDownIcon_ from '../assets/icons/arrow-down.svg';
import BuisnessProcessesIcon_ from '../assets/icons/buisness-processes.svg';
import CaretIcon_ from '../assets/icons/caret.svg';
import CheckMarkIcon_ from '../assets/icons/check-mark.svg';
import CrossIcon_ from '../assets/icons/cross.svg';
import DotsIcon_ from '../assets/icons/dots.svg';
import ExitIcon_ from '../assets/icons/exit.svg';
import EyeClosedIcon_ from '../assets/icons/eye-closed.svg';
import EyeIcon_ from '../assets/icons/eye.svg';
import HomeIcon_ from '../assets/icons/home.svg';
import IMarkIcon_ from '../assets/icons/i-mark.svg';
import PlayIcon_ from '../assets/icons/play.svg';
import PlusIcon_ from '../assets/icons/plus.svg';
import RuntimeEnvironmentsIcon_ from '../assets/icons/runtime-environments.svg';
import SearchIcon_ from '../assets/icons/search.svg';
import ServersIcon_ from '../assets/icons/servers.svg';
import ServicesIcon_ from '../assets/icons/services.svg';
import SettingsIcon_ from '../assets/icons/settings.svg';
import SoftwareIcon_ from '../assets/icons/software.svg';
import StartBlueIcon_ from '../assets/icons/start-blue.svg';
import StartsIcon_ from '../assets/icons/starts.svg';
import StopIcon_ from '../assets/icons/stop.svg';
import StrokeIcon_ from '../assets/icons/stroke.svg';
import TasksIcon_ from '../assets/icons/tasks.svg';
import TrashIcon_ from '../assets/icons/trash.svg';
import TriggersIcon_ from '../assets/icons/triggers.svg';
import UsersIcon_ from '../assets/icons/users.svg';
import WarningIcon_ from '../assets/icons/warning.svg';
import WorksTuzIcon_ from '../assets/icons/works-tuz.svg';
import XMarkSmallIcon_ from '../assets/icons/x-mark-small.svg';
import XMarkIcon_ from '../assets/icons/x-mark.svg';
import CaretSmallIcon_ from '../assets/icons/caret-small.svg';

// console.log('CaretSmallIcon_', CaretSmallIcon_);

const SvgImg = ({ ...args }) => {
    const { svg, alt = '' } = args;
    delete args.svg;
    delete args.alt;
    return <img {...args} alt={alt} src={svg} />;
};

export const ArrowDownIcon = (...args: any) => <SvgImg {...args} svg={ArrowDownIcon_} />;
export const BuisnessProcessesIcon = (...args: any) => <SvgImg {...args} svg={BuisnessProcessesIcon_} />;
export const CaretIcon = (...args: any) => <SvgImg {...args} svg={CaretIcon_} />;
export const CheckMarkIcon = (...args: any) => <SvgImg {...args} svg={CheckMarkIcon_} />;
export const CrossIcon = (...args: any) => <SvgImg {...args} svg={CrossIcon_} />;
export const DotsIcon = (...args: any) => <SvgImg {...args} svg={DotsIcon_} />;
export const ExitIcon = (...args: any) => <SvgImg {...args} svg={ExitIcon_} />;
export const EyeClosedIcon = (...args: any) => <SvgImg {...args} svg={EyeClosedIcon_} />;
export const EyeIcon = (...args: any) => <SvgImg {...args} svg={EyeIcon_} />;
export const HomeIcon = (...args: any) => <SvgImg {...args} svg={HomeIcon_} />;
export const IMarkIcon = (...args: any) => <SvgImg {...args} svg={IMarkIcon_} />;
export const PlayIcon = (...args: any) => <SvgImg {...args} svg={PlayIcon_} />;
export const PlusIcon = (...args: any) => <SvgImg {...args} svg={PlusIcon_} />;
export const RuntimeEnvironmentsIcon = (...args: any) => <SvgImg {...args} svg={RuntimeEnvironmentsIcon_} />;
export const SearchIcon = (...args: any) => <SvgImg {...args} svg={SearchIcon_} />;
export const ServersIcon = (...args: any) => <SvgImg {...args} svg={ServersIcon_} />;
export const ServicesIcon = (...args: any) => <SvgImg {...args} svg={ServicesIcon_} />;
export const SettingsIcon = (...args: any) => <SvgImg {...args} svg={SettingsIcon_} />;
export const SoftwareIcon = (...args: any) => <SvgImg {...args} svg={SoftwareIcon_} />;
export const StartBlueIcon = (...args: any) => <SvgImg {...args} svg={StartBlueIcon_} />;
export const StartsIcon = (...args: any) => <SvgImg {...args} svg={StartsIcon_} />;
export const StopIcon = (...args: any) => <SvgImg {...args} svg={StopIcon_} />;
export const StrokeIcon = (...args: any) => <SvgImg {...args} svg={StrokeIcon_} />;
export const TasksIcon = (...args: any) => <SvgImg {...args} svg={TasksIcon_} />;
export const TrashIcon = (...args: any) => <SvgImg {...args} svg={TrashIcon_} />;
export const TriggersIcon = (...args: any) => <SvgImg {...args} svg={TriggersIcon_} />;
export const UsersIcon = (...args: any) => <SvgImg {...args} svg={UsersIcon_} />;
export const WarningIcon = (...args: any) => <SvgImg {...args} svg={WarningIcon_} />;
export const WorksTuzIcon = (...args: any) => <SvgImg {...args} svg={WorksTuzIcon_} />;
export const XMarkSmallIcon = (...args: any) => <SvgImg {...args} svg={XMarkSmallIcon_} />;
export const XMarkIcon = (...args: any) => <SvgImg {...args} svg={XMarkIcon_} />;
export const CaretSmallIcon = (...args: any) => <SvgImg {...args} svg={CaretSmallIcon_} />;
